name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Build Release
        run: swift build -c release
      - name: Run tests
        run: swift test
      - name: Restart Vapor Server
        run: supervisorctl restart swiftware-server
