name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Build Debug
        run: swift build -v
      - name: Run tests
        run: swift test -v
      - name: Build Release
        run: swift build -c release
